### ISSUE TITLE
[request] Don't retrieve missing Specials

### ISSUE THREAD

**Issue by neopc10** [jellyfin/jellyfin-plugin-tvdb#41]
For many shows there are deleted scenes or interviews or DVD extras that the plugin will retrieve and populate into Jellyfin. I don't think the average user is interested in these as they are upcoming episodes or missing episodes assuming they have this provider enabled.

**Comment by NunoMouraz** [comment]
Where I feel its more intrusive its when Specials are shown inside a numbered Season. I'm not sure if this is intended behaviour, or its tvtb's fault.
Its even more intrusive since sometimes its shown between Episode X and Episode Y, instead of showing at the end/start of the season. In any case it might be correct since sometimes there are 'Specials' where the events transpired are actually between mentioned episode X and Y; This happens more often in anime.
