### ISSUE TITLE
Allow using alternate order

### ISSUE THREAD

**Issue by TheChilliPL** [jellyfin/jellyfin-plugin-tvdb#49]
I believe the plugin doesn't allow using alternate episode orders, which would be great
And example of a series with alternative order is [La casa de papel](https://www.thetvdb.com/series/la-casa-de-papel).

The “official” order is:
![image](https://user-images.githubusercontent.com/18823939/132125603-32aac058-c679-4386-a5d4-94ef16770a57.png)

Though one may want to use the Netflix order:
![image](https://user-images.githubusercontent.com/18823939/132125620-ef360e06-a2a8-479a-a301-90d5db7ef67c.png)

I presume there could be some way to change the order of a single show, and keep the current behavior as default.

**Comment by cvium** [comment]
Their API v3 doesn't allow it. Maybe in v4...

**Comment by TheChilliPL** [comment]
[API v4 endpoint `/lists`](https://thetvdb.github.io/v4-api/#/Lists/getAllLists) returns something like
```json
{
  "data": [
    {
      "aliases": [
        {
          "language": "string",
          "name": "string"
        }
      ],
      "id": 0,
      "isOfficial": true,
      "name": "string",
      "nameTranslations": [
        "string"
      ],
      "overview": "string",
      "overviewTranslations": [
        "string"
      ],
      "url": "string"
    }
  ],
  "status": "string"
}
```
I guess it may be for that? Not sure.
I see you already have [an issue about that](#47) open, but I'll leave this one open too.
Looking forward for the option, good luck!

**Comment by TheChilliPL** [comment]
Or possibly the [`/series/:id/episodes/:season-type` endpoint](https://thetvdb.github.io/v4-api/#/default/getSeriesEpisodes)
![image](https://user-images.githubusercontent.com/18823939/132129063-e5d61024-fae4-421a-bf84-08bef23f7955.png)

**Comment by mmBesar** [comment]
Yes, this is will come with API V4.

**Comment by fir3-1ce** [comment]
Is there any update on this? I have a series that I would like to use the "Saga" order, which according to TVDB is accessible via Alternate Order

**Comment by CarlMichaelFabe** [comment]
Any updates?

**Comment by Kianda** [comment]
Adding more info on this issue using 'The Office' as example, hope this can help!

**TVDB Ids**
Show: 73244
S09 "alternate" order: 1833510
S09E26 on "alternate" order: 7937344
S09E27 on "alternate" order: 7937345
Swagger: https://thetvdb.github.io/v4-api/ (to use this you need a API Key)

**Steps to reproduce**
1. Create a folder into your tv shows library and name it "The Office (US) - [tvdbid-73244]"
2. Into this folder create another one and name it "S09"
3. Into this "S09" folder then place two random video files and call them "S09E26" & "S09E27"
4. Go to Jellyfin and execute a scan

**Issue**
As you see here https://thetvdb.com/series/the-office-us#seasons the episodes 26 and 27 are only into Season 9 in the "Amazon Order"/"alternate" ordering.
There is no way to tell Jellyfin to read the "Amazon Order"/"alternate" from thetvdb.com and because of this it can't get the data of "S09E26" & "S09E27"

**Additional**
The TVDB Api endpoint _/seasons/types_ gives this result -> https://jsonblob.com/1222864521088851968
The "Amazon Order" should be the "alternate" type but it seems that Jellyfin does not support this type of ordering.
Here the response from TVDB Api endpoint _/seasons/1833510/extended_ -> http://jsonblob.com/1222863909571911680
Manually setting the "TVDB Season ID" on the Season 9 or even the "TVDB Episode ID" on the single "S09E26"/"S09E27" does not work :(

Any ideas on how to solve this on Jellyfin?

**Comment by scampower3** [comment]
While I think this is implementable, it will require some arbitrary mappings that might not be intuitive for the end-user since out of all the orders provided by the Tvdb api, Jellyfin only supports aired, absolute and dvd. The rest will have to be arbitrarily mapped, like Jellyfin's "Story Arc" option could be mapped to Tvdb's "alternate".

@crobibero thoughts?

**Comment by crobibero** [comment]
I think we could expand Jellyfin's display order? At the same time it would be nice to have it as an enum instead of a free string
